const Cards = [
  // Spades (♠)
  { id: 1, cardType: "French", name: "♠Ace", effect: "Vízesés, balra", color: "black", src: "/CardImages/spades/1AceOfSpades.png" },
  { id: 2, cardType: "French", name: "♠2", effect: "Coinflip duel", color: "black", src: "/CardImages/spades/2OfSpades.png" },
  { id: 3, cardType: "French", name: "♠3", effect: "Igyál 3 kortyot", color: "black", src: "/CardImages/spades/3OfSpades.png" },
  { id: 4, cardType: "French", name: "♠4", effect: "Igyál 4 kortyot", color: "black", src: "/CardImages/spades/4OfSpades.png" },
  { id: 5, cardType: "French", name: "♠5", effect: "Igyál 5 kortyot", color: "black", src: "/CardImages/spades/5OfSpades.png" },
  { id: 6, cardType: "French", name: "♠6", effect: "Ha fiú húzza, kioszt 6-ot, ha lány húzza, iszik 6-ot", color: "black", src: "/CardImages/spades/6OfSpades.png" },
  { id: 7, cardType: "French", name: "♠7", effect: "Drink or dare", color: "black", src: "/CardImages/spades/7OfSpades.png" },
  { id: 8, cardType: "French", name: "♠8", effect: "D20", color: "black", src: "/CardImages/spades/8OfSpades.png" },
  { id: 9, cardType: "French", name: "♠9", effect: "Blood Brother", color: "black", src: "/CardImages/spades/9OfSpades.png" },
  { id: 10, cardType: "French", name: "♠10", effect: "Új szabály", color: "black", src: "/CardImages/spades/10OfSpades.png" },
  { id: 11, cardType: "French", name: "♠Jack", effect: "Annyi korty minden fiúnak, ahány fiú van", color: "black", src: "/CardImages/spades/11JackOfSpades.png" },
  { id: 12, cardType: "French", name: "♠Queen", effect: "Annyi korty minden lánynak, ahány lány van", color: "black", src: "/CardImages/spades/12QueenOfSpades.png" },
  { id: 13, cardType: "French", name: "♠King", effect: "Király", color: "black", src: "/CardImages/spades/13KingOfSpades.png" },

  // Hearts (♥)
  { id: 14, cardType: "French", name: "♥Ace", effect: "Vízesés, jobbra", color: "red", src: "/CardImages/hearts/1AceOfHearts.png" },
  { id: 15, cardType: "French", name: "♥2", effect: "Coinflip duel", color: "red", src: "/CardImages/hearts/2OfHearts.png" },
  { id: 16, cardType: "French", name: "♥3", effect: "Ossz ki 3 kortyot", color: "red", src: "/CardImages/hearts/3OfHearts.png" },
  { id: 17, cardType: "French", name: "♥4", effect: "Ossz ki 4 kortyot", color: "red", src: "/CardImages/hearts/4OfHearts.png" },
  { id: 18, cardType: "French", name: "♥5", effect: "Ossz ki 5 kortyot", color: "red", src: "/CardImages/hearts/5OfHearts.png" },
  { id: 19, cardType: "French", name: "♥6", effect: "Ha lány húzza, kioszt 6-ot, ha fiú húzza, iszik 6-ot", color: "red", src: "/CardImages/hearts/6OfHearts.png" },
  { id: 20, cardType: "French", name: "♥7", effect: "Drink or dare", color: "red", src: "/CardImages/hearts/7OfHearts.png" },
  { id: 21, cardType: "French", name: "♥8", effect: "D20", color: "red", src: "/CardImages/hearts/8OfHearts.png" },
  { id: 22, cardType: "French", name: "♥9", effect: "Blood Brother", color: "red", src: "/CardImages/hearts/9OfHearts.png" },
  { id: 23, cardType: "French", name: "♥10", effect: "Új szabály", color: "red", src: "/CardImages/hearts/10OfHearts.png" },
  { id: 24, cardType: "French", name: "♥Jack", effect: "Annyi korty minden fiúnak, ahány fiú van", color: "red", src: "/CardImages/hearts/11JackOfHearts.png" },
  { id: 25, cardType: "French", name: "♥Queen", effect: "Annyi korty minden lánynak, ahány lány van", color: "red", src: "/CardImages/hearts/12QueenOfHearts.png" },
  { id: 26, cardType: "French", name: "♥King", effect: "Király", color: "red", src: "/CardImages/hearts/13KingOfHearts.png" },

  // Diamonds (♦)
  { id: 27, cardType: "French", name: "♦Ace", effect: "Vízesés, jobbra", color: "red", src: "/CardImages/diamonds/1AceOfDiamonds.png" },
  { id: 28, cardType: "French", name: "♦2", effect: "Coinflip duel", color: "red", src: "/CardImages/diamonds/2OfDiamonds.png" },
  { id: 29, cardType: "French", name: "♦3", effect: "Ossz ki 3 kortyot", color: "red", src: "/CardImages/diamonds/3OfDiamonds.png" },
  { id: 30, cardType: "French", name: "♦4", effect: "Ossz ki 4 kortyot", color: "red", src: "/CardImages/diamonds/4OfDiamonds.png" },
  { id: 31, cardType: "French", name: "♦5", effect: "Ossz ki 5 kortyot", color: "red", src: "/CardImages/diamonds/5OfDiamonds.png" },
  { id: 32, cardType: "French", name: "♦6", effect: "Ha lány húzza, kioszt 6-ot, ha fiú húzza, iszik 6-ot", color: "red", src: "/CardImages/diamonds/6OfDiamonds.png" },
  { id: 33, cardType: "French", name: "♦7", effect: "Drink or dare", color: "red", src: "/CardImages/diamonds/7OfDiamonds.png" },
  { id: 34, cardType: "French", name: "♦8", effect: "D20", color: "red", src: "/CardImages/diamonds/8OfDiamonds.png" },
  { id: 35, cardType: "French", name: "♦9", effect: "Blood Brother", color: "red", src: "/CardImages/diamonds/9OfDiamonds.png" },
  { id: 36, cardType: "French", name: "♦10", effect: "Új szabály", color: "red", src: "/CardImages/diamonds/10OfDiamonds.png" },
  { id: 37, cardType: "French", name: "♦Jack", effect: "Annyi korty minden fiúnak, ahány fiú van", color: "red", src: "/CardImages/diamonds/11JackOfDiamonds.png" },
  { id: 38, cardType: "French", name: "♦Queen", effect: "Annyi korty minden lánynak, ahány lány van", color: "red", src: "/CardImages/diamonds/12QueenOfDiamonds.png" },
  { id: 39, cardType: "French", name: "♦King", effect: "Király", color: "red", src: "/CardImages/diamonds/13KingOfDiamonds.png" },

  // Clubs (♣)
  { id: 40, cardType: "French", name: "♣Ace", effect: "Vízesés, balra", color: "black", src: "/CardImages/clubs/1AceOfClubs.png" },
  { id: 41, cardType: "French", name: "♣2", effect: "Coinflip duel", color: "black", src: "/CardImages/clubs/2OfClubs.png" },
  { id: 42, cardType: "French", name: "♣3", effect: "Igyál 3 kortyot", color: "black", src: "/CardImages/clubs/3OfClubs.png" },
  { id: 43, cardType: "French", name: "♣4", effect: "Igyál 4 kortyot", color: "black", src: "/CardImages/clubs/4OfClubs.png" },
  { id: 44, cardType: "French", name: "♣5", effect: "Igyál 5 kortyot", color: "black", src: "/CardImages/clubs/5OfClubs.png" },
  { id: 45, cardType: "French", name: "♣6", effect: "Ha fiú húzza, kioszt 6-ot, ha lány húzza, iszik 6-ot", color: "black", src: "/CardImages/clubs/6OfClubs.png" },
  { id: 46, cardType: "French", name: "♣7", effect: "Drink or dare", color: "black", src: "/CardImages/clubs/7OfClubs.png" },
  { id: 47, cardType: "French", name: "♣8", effect: "D20", color: "black", src: "/CardImages/clubs/8OfClubs.png" },
  { id: 48, cardType: "French", name: "♣9", effect: "Blood Brother", color: "black", src: "/CardImages/clubs/9OfClubs.png" },
  { id: 49, cardType: "French", name: "♣10", effect: "Új szabály", color: "black", src: "/CardImages/clubs/10OfClubs.png" },
  { id: 50, cardType: "French", name: "♣Jack", effect: "Annyi korty minden fiúnak, ahány fiú van", color: "black", src: "/CardImages/clubs/11JackOfClubs.png" },
  { id: 51, cardType: "French", name: "♣Queen", effect: "Annyi korty minden lánynak, ahány lány van", color: "black", src: "/CardImages/clubs/12QueenOfClubs.png" },
  { id: 52, cardType: "French", name: "♣King", effect: "Király", color: "black", src: "/CardImages/clubs/13KingOfClubs.png" },

  // SPECTRAL
  { id: 53, cardType: "SPECTRAL", name: "Ankh", effect: "A szorzód 1-re, a plusz kortyaid pedig 0-ra állítódnak (ha negatívak a plusz kortyaid, akkor változatlanul maradnak)", color: "-", src: "/CardImages/SPECTRAL/ankh.png" },
  { id: 54, cardType: "SPECTRAL", name: "Aura", effect: "Mindenki akinek eddig a tesója voltál, mostantól a tesód", color: "-", src: "/CardImages/SPECTRAL/aura.png" },
  { id: 55, cardType: "SPECTRAL", name: "Black hole", effect: "Mindenki befejezi az italát, viszont aki felhúzta, az előtte újratölti az övét", color: "-", src: "/CardImages/SPECTRAL/black hole.png" },
  { id: 56, cardType: "SPECTRAL", name: "Cryptid", effect: "Általad válaszott játékos dob egyet a D20-al, ha nem 20-ast dobott akkor iszik egy kortyot, addig ismétli amég nem sikerül 20-ast dobnia", color: "-", src: "/CardImages/SPECTRAL/cryptid.png" },
  { id: 57, cardType: "SPECTRAL", name: "Deja vu", effect: "Az előző körben játszott lapodat újra kijátszod", color: "-", src: "/CardImages/SPECTRAL/deja vu.png" },
  { id: 58, cardType: "SPECTRAL", name: "Ectoplasm", effect: "Igyál annyi kortyot, ahány éves vagy /2", color: "-", src: "/CardImages/SPECTRAL/ectoplasm.png" },
  { id: 59, cardType: "SPECTRAL", name: "Familiar", effect: "Keverj egy italt, majd válassz valakit akivel elfelezed", color: "-", src: "/CardImages/SPECTRAL/familiar.png" },
  { id: 60, cardType: "SPECTRAL", name: "Grim", effect: "Dobj egyet egy D6-al, majd idd meg a dobott szám négyzetét", color: "-", src: "/CardImages/SPECTRAL/grim.png" },
  { id: 61, cardType: "SPECTRAL", name: "Hex", effect: "Sózd meg az italod (ízlés szerint xd)", color: "-", src: "/CardImages/SPECTRAL/hex.png" },
  { id: 62, cardType: "SPECTRAL", name: "Immolate", effect: "Rakj valami csípőset az italodba xd", color: "-", src: "/CardImages/SPECTRAL/immolate.png" },
  { id: 63, cardType: "SPECTRAL", name: "Incantation", effect: "A következő 5 lapot te húzod fel", color: "-", src: "/CardImages/SPECTRAL/incantation.png" },
  { id: 64, cardType: "SPECTRAL", name: "Medium", effect: "Választhatsz egy francia kártyát amiből 3 db belekeveredik a pakliba", color: "-", src: "/CardImages/SPECTRAL/medium.png" },
  { id: 65, cardType: "SPECTRAL", name: "Ouija", effect: "Választhatsz egy lapot az általad kijátszott lapok közül, amit megkapsz megint", color: "-", src: "/CardImages/SPECTRAL/ouija.png" },
  { id: 66, cardType: "SPECTRAL", name: "Sigil", effect: "Húzhatsz mégegy lapot, ami 2x játszódik ki", color: "-", src: "/CardImages/SPECTRAL/sigil.png" },
  { id: 67, cardType: "SPECTRAL", name: "Soul", effect: "A következő italodba nem rakhatsz alkoholt, pihenj egy picit", color: "-", src: "/CardImages/SPECTRAL/soul.png" },
  { id: 68, cardType: "SPECTRAL", name: "Talisman", effect: "A kör végén kapsz 2 random SPECTRAL lapot", color: "-", src: "/CardImages/SPECTRAL/talisman.png" },
  { id: 69, cardType: "SPECTRAL", name: "Trance", effect: "Minden kártya amit a játék alatt felhúztál visszakeveredik a pakliba", color: "-", src: "/CardImages/SPECTRAL/trance.png" },
  { id: 70, cardType: "SPECTRAL", name: "Wraith", effect: "Tölts ki 1 shotnyi vizet és 1 shotnyi átlátszó alkoholt, majd válassz valakit aki eldöntheti hogy melyiket issza meg, te pedig idd meg a másikat", color: "-", src: "/CardImages/SPECTRAL/wraith.png" },

];

module.exports = Cards;
